{{ if .Values.nuviostreams.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-nuviostreams.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-nuviostreams.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: nuviostreams
          kind: Service
          port: 7777
      middlewares:
        - name: headers-add-cors-for-stremio
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-nuviostreams.{{ .Values.dns_domain }}`) && (PathPrefix(`/configure`) || PathRegexp(`^/(.*)configure`) || PathPrefix(`/_oauth`))
      kind: Rule
      services:
        - name: nuviostreams
          kind: Service
          port: 7777
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: chain-hosted-stremio-addon
          namespace: traefik

{{ end }}