{{ if .Values.cleanuparr.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-cleanuparr.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-cleanuparr.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: cleanuparr
          kind: Service
          port: 11011
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}