{{ if .Values.stremthru.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-stremthru.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-stremthru.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: stremthru
          kind: Service
          port: 8080
      middlewares:
        - name: headers-add-cors-origin-any
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-stremthru.{{ .Values.dns_domain }}`) && (PathRegexp(`^/(.*)/configure`) || PathPrefix(`/_oauth`))
      kind: Rule
      services:
        - name: stremthru
          kind: Service
          port: 8080
      middlewares:
      {{ if not .Values.mediafusionexposed.enabled }}
        - name: {{ .Release.Name }}-traefik-forward-auth
      {{ end }}
        - name: chain-hosted-stremio-addon
          namespace: traefik          
    # Block URLs we don't want public access to
    - match: Host(`{{ .Release.Name }}-stremthru.{{ .Values.dns_domain }}`) && PathPrefix(`/v0/store/magnets/check`) 
      kind: Rule
      services:
        - name: stremthru
          kind: Service
          port: 8080
      middlewares:  
        - name: ipallowlist-localhost-only
          namespace: traefik
    # Allow speedtest on /speed
    - match: Host(`{{ .Release.Name }}-stremthru.{{ .Values.dns_domain }}`) && PathPrefix(`/speed`)
      kind: Rule
      services:
        - name: stremthru
          kind: Service
          port: 3002 # openspeedtest
      middlewares:
        - name: stripprefix-speed
          namespace: traefik
        - name: buffer-2gb
          namespace: traefik
{{ end }}