{{ if .Values.mediaflowproxy.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-mediaflow-proxy.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-mediaflow-proxy.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: mediaflow-proxy
          kind: Service
          port: 8888
    - match: Host(`{{ .Release.Name }}-mediaflow-proxy.{{ .Values.dns_domain }}`) && (PathPrefix(`/speed`) && !PathPrefix(`/speedtest`))
      kind: Rule
      services:
        - name: mediaflow-proxy
          kind: Service
          port: 3002 # openspeedtest
      middlewares:
        - name: stripprefix-speed
          namespace: traefik
        - name: buffer-2gb
          namespace: traefik
{{ end }}