{{ if .Values.listsync.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-listsync-api.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-listsync-api.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: listsync
          kind: Service
          port: 4222
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}