{{ if or .Values.plex.enabled  .Values.plexranger.enabled .Values.plexhobbit.enabled .Values.plexhalfling.enabled .Values.plexnazgul.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-plex.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-plex.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: plex
          kind: Service
          port: 32400
    - match: Host(`{{ .Release.Name }}-plex.{{ .Values.dns_domain }}`) && PathPrefix(`/speed`)
      kind: Rule
      services:
        - name: plex
          kind: Service
          port: 3002 # openspeedtest
      middlewares:
        - name: stripprefix-speed
          namespace: traefik        
        - name: buffer-2gb
          namespace: traefik
{{ end }}