{{ if .Values.wger.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-wger.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-wger.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: wger
          kind: Service
          port: 8000
      middlewares:  
        - name: error-pages
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-wger.{{ .Values.dns_domain }}`) && (PathPrefix(`/static/`) || PathPrefix(`/media/`))
      kind: Rule
      services:
        - name: wger
          kind: Service
          port: 8080
      middlewares:  
        - name: error-pages
          namespace: traefik
{{ end }}