{{ if .Values.peertube.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-peertube-cli.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-peertube-cli.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: peertube
          kind: Service
          port: 3001
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}