{{ if .Values.radarr4k.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-radarr4k.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-radarr4k.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: radarr4k
          kind: Service
          port: 7878
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: {{ .Release.Name }}-add-cors-for-homer
        - name: error-pages
          namespace: traefik
        - name: radarr-4k
          namespace: traefik
    # Allow API tests without auth (necessary for ajax responses)
    - match: Host(`{{ .Release.Name }}-radarr4k.{{ .Values.dns_domain }}`) && PathRegexp(`^/api/(.+)/test`)
      kind: Rule
      services:
        - name: radarr4k
          kind: Service
          port: 7878
    {{ if .Values.radarr4kexposed.enabled }}
    - match: Host(`{{ .Release.Name }}-radarr4k.{{ .Values.dns_domain }}`) && PathPrefix(`/api/`)
      kind: Rule
      services:
        - name: radarr4k
          kind: Service
          port: 7878
      middlewares:      
        - name: {{ .Release.Name }}-add-cors-for-homer
    {{ end }}
{{ end }}