{{ if .Values.discovarr.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-discovarr.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-discovarr.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: discovarr
          kind: Service
          port: 8000
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
{{ end }}