{{ if .Values.nuviostreams.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-nuviostreams-proxy.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-nuviostreams-proxy.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: nuviostreams
          kind: Service
          port: 3000
{{ end }}