{{ if .Values.comet.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-comet.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-comet.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: comet
          kind: Service
          port: 8000
      middlewares:
        - name: headers-add-cors-origin-any
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-comet.{{ .Values.dns_domain }}`) && (PathPrefix(`/configure`) || PathRegexp(`^/(.*)configure`) || PathPrefix(`/_oauth`))
      kind: Rule
      services:
        - name: comet
          kind: Service
          port: 8000
      middlewares:
      {{ if not .Values.cometexposed.enabled }}
        - name: {{ .Release.Name }}-traefik-forward-auth
      {{ end }}
        - name: chain-hosted-stremio-addon
          namespace: traefik
{{ end }}