{{ if .Values.aiostreams.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-aiostreams.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-aiostreams.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: aiostreams
          kind: Service
          port: 3000
      middlewares:
        - name: headers-add-cors-for-stremio
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-aiostreams.{{ .Values.dns_domain }}`) && (PathPrefix(`/stremio/configure`) || PathRegexp(`^/(.*)configure`) || PathPrefix(`/_oauth`))
      kind: Rule
      services:
        - name: aiostreams
          kind: Service
          port: 3000
      middlewares:
      {{ if not .Values.aiostreamsexposed.enabled }}
        - name: {{ .Release.Name }}-traefik-forward-auth
      {{ end }}
        - name: chain-hosted-stremio-addon
          namespace: traefik

{{ end }}