{{ if .Values.actual.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-actual-api.{{ .Values.dns_domain }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Release.Name }}-actual-api.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: actual
          kind: Service
          port: 5007
{{ end }}