{{- if .Values.peertubecustomdomain.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.peertubecustomdomain.cname | lower }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Values.peertubecustomdomain.cname | lower }}`)
      kind: Rule
      services:
        - name: peertube
          kind: Service
          port: 9000
  tls:
    secretName: cert-{{ .Values.peertubecustomdomain.cname | lower }}
{{ end }}