{{- if .Values.actualapicustomdomain.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.actualapicustomdomain.cname | lower }}
spec:
  entryPoints:
  - websecure
  routes:
    - match: Host(`{{ .Values.actualapicustomdomain.cname | lower }}`)
      kind: Rule
      services:
        - name: actual
          kind: Service
          port: 5007
  tls:
    secretName: cert-{{ .Values.actualapicustomdomain.cname | lower }}
{{ end }}