{{ if .Values.elfbot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elfbot
  labels:
    app.kubernetes.io/name: elfbot
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: elfbot
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}