{{ if .Values.rclonemountalldebrid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: alldebrid
  labels:
    app.kubernetes.io/name: rclonealldebrid
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: http
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: tinyproxy
  selector:
    app.kubernetes.io/name: rclonealldebrid
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}