{{ if .Values.rclonetorbox.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: torbox
  labels:
    app.kubernetes.io/name: rclonetorbox
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: rclonetorbox
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}