{{ if .Values.decypharr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: decypharr
  labels:
    app.kubernetes.io/name: decypharr
    app.kubernetes.io/instance: {{ .Release.Name }}
    zilean.elfhosted.com/scrape: "decypharr"
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8282
    targetPort: 8282
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: decypharr
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}