{{ if .Values.cinesync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cinesync
  labels:
    app.kubernetes.io/name: cinesync
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: cinesync
  selector:
    app.elfhosted.com/name: cinesync
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}