{{ if .Values.peertube.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: peertube
  labels:
    app.kubernetes.io/name: peertube
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: cli   
  selector:
    app.kubernetes.io/name: peertube
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}