{{ if or .Values.jellyfin.enabled .Values.jellyfinranger.enabled .Values.jellyfinhobbit.enabled .Values.jellyfinhalfling.enabled .Values.jellyfinnazgul.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app.elfhosted.com/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8096
    targetPort: 8096
    protocol: TCP
    name: http
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: jellyfixer
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: speedtest    
  selector:
    app.elfhosted.com/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}    
{{ end }}    