{{ if .Values.nuviostreams.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nuviostreams
  labels:
    app.kubernetes.io/name: nuviostreams
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 7777
    targetPort: 7777
    protocol: TCP
    name: http
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: simple-proxy
  selector:
    app.kubernetes.io/name: nuviostreams
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}