{{ if .Values.plexrequests.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plexrequests
  labels:
    app.kubernetes.io/name: plexrequests
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 32501
    targetPort: 32501
    protocol: TCP
    name: auth
  - port: 32502
    targetPort: 32502
    protocol: TCP
    name: request
  selector:
    app.kubernetes.io/name: plexrequests
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}