{{ if .Values.wger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wger
  labels:
    app.kubernetes.io/name: wger
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: nginx    
  selector:
    app.kubernetes.io/name: wger
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}    