{{ if .Values.rclonedebridlink.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: debridlink
  labels:
    app.kubernetes.io/name: debridlink
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: rclonedebridlink
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}