{{ if .Values.plexytrack.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plexytrack
  labels:
    app.kubernetes.io/name: plexytrack
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 5030
    targetPort: 5030
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: plexytrack
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}