{{ if .Values.cleanuparr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
  labels:
    app.kubernetes.io/name: rcleanuparr
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 11011
    targetPort: 11011
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: cleanuparr
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}