{{ if or .Values.plex.enabled .Values.plexranger.enabled .Values.plexhobbit.enabled .Values.plexhalfling.enabled .Values.plexnazgul.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: plex-proxy
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app.elfhosted.com/name: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}