{{ if .Values.channelsdvr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: channelsdvr
  labels:
    app.kubernetes.io/name: channelsdvr
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: speed
  selector:
    app.kubernetes.io/name: channelsdvr
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}