{{ if .Values.stremthru.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: stremthru
  labels:
    app.kubernetes.io/name: stremthru
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: speedtest
  selector:
    app.kubernetes.io/name: stremthru
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}