{{ if or .Values.flaresolverr.enabled .Values.byparr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8191
    targetPort: 8191
    protocol: TCP
    name: http
  selector:
    {{- if and (not .Values.flaresolverr.enabled) .Values.byparr.enabled }}
    app.kubernetes.io/name: byparr
    {{- else }}
    app.kubernetes.io/name: flaresolverr
    {{- end }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}