{{ if .Values.mediamanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: media-manager
  labels:
    app.kubernetes.io/name: media-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.elfhosted.com/name: media-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}