{{ if .Values.actual.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 5006
    targetPort: 5006
    protocol: TCP
    name: http
  - port: 5007
    targetPort: 5007
    protocol: TCP
    name: api    
  selector:
    app.kubernetes.io/name: actual
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}