{{ if .Values.byparr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: byparr
  labels:
    app.kubernetes.io/name: byparr
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8191
    targetPort: 8191
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: byparr
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}