apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: rd-backup
spec:
  trigger:
    manual: runonce
  restic:
    repository: backup-volsync-restic-config
    copyMethod: Snapshot
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: 
        - labelSelector:
            matchExpressions:
            - key: app.elfhosted.com/role
              operator: In
              values:
              - nodefinder
          topologyKey: "kubernetes.io/hostname"
    cacheCapacity: 20Gi
    capacity: 20Gi
    cacheStorageClassName: topolvm-provisioner-thin
    accessModes:
    - ReadWriteOnce
    storageClassName: topolvm-provisioner-thin
    cacheAccessModes:
    - ReadWriteOnce
    volumeSnapshotClassName: topolvm-provisioner-thin