{{ if or .Values.zurg.enabled .Values.zurggluetun.enabled .Values.zurgranger.enabled .Values.zurghobbit.enabled .Values.zurghalfling.enabled .Values.zurgnazgul.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zurg-env
data:
  LOG_LEVEL: debug
  {{ if .Values.decypharrreplacezurg.enabled }}
  DECYPHARR_REPLACE_ZURG: "true"
  {{ end }}
{{ end }}