{{ if .Values.peertube.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: peertube-env
data:
  # Database / Postgres service configuration

  PEERTUBE_DB_USERNAME: peertube
  # PEERTUBE_DB_PASSWORD: set in secret
  PEERTUBE_DB_SSL: "false"
  # Default to Postgres service name "postgres" in docker-compose.yml
  PEERTUBE_DB_HOSTNAME: localhost

  # PeerTube server configuration
  # If you test PeerTube in local: use "peertube.localhost" and add this domain to your host file resolving on 127.0.0.1
  PEERTUBE_WEBSERVER_HOSTNAME: {{ .Release.Name }}-peertube.{{ .Values.dns_domain }}
  # If you just want to test PeerTube on local
  PEERTUBE_WEBSERVER_PORT: "443"
  PEERTUBE_WEBSERVER_HTTPS: "true"

  # PEERTUBE_REDIS_HOSTNAME: redis-headless
  # PEERTUBE_REDIS_PORT: "6379"

  # /!\ Prefer to use the PeerTube admin interface to set the following configurations /!\
  PEERTUBE_SIGNUP_ENABLED: "false"
  PEERTUBE_TRANSCODING_ENABLED: "true"
  PEERTUBE_CONTACT_FORM_ENABLED: "true"


  
{{ end }}
