{{ if .Values.zurg.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zurg-env
data:
  LOG_LEVEL: debug
  {{ if .Values.decypharrreplacezurg.enabled }}
  FOR_FUTURE_DECYPHARR_REPLACE_ZURG: "true"
  {{ end }}
{{ end }}