{{ if .Values.discovarr.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: discovarr-env
data:
  VITE_DISCOVARR_URL: https://{{ .Release.Name }}-discovarr.{{ .Values.dns_domain }}/api
{{ end }}
