{{ if .Values.cinesync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinesync-env
data:
  SOURCE_DIR: {{ $dirs := list }}
    {{ if .Values.rclonemountrealdebridzurg.enabled }}{{ $dirs = append $dirs "/storage/realdebrid-zurg/__all__" }}{{- end }}
    {{- if .Values.rclonealldebrid.enabled }}{{ $dirs = append $dirs "/storage/alldebrid/magnets" }}{{- end }}
    {{- if .Values.rclonetorbox.enabled }}{{ $dirs = append $dirs "/storage/torbox" }}{{- end }}
    {{- if .Values.rclonedebridlink.enabled }}{{ $dirs = append $dirs "/storage/debridlink" }}{{- end }}
    {{- if .Values.rclonepremiumize.enabled }}{{ $dirs = append $dirs "/storage/premiumize" }}{{- end }}
    {{- join "," $dirs }}
  DESTINATION_DIR: /storage/symlinks
  RCLONE_MOUNT: "true"
  {{ if or .Values.plex.enabled .Values.plexranger.enabled .Values.plexhobbit.enabled .Values.plexhalfling.enabled .Values.plexnazgul.enabled }}
  ENABLE_PLEX_UPDATE: "true"
  PLEX_URL: http://plex:32400
  {{ end }}
  RENAME_ENABLED: "true"
  TMDB_FOLDER_ID: "true"
  RENAME_TAGS: VideoCodec,DynamicRange,AudioCodec,AudioChannels,AudioAtmos,StreamingServices,Languages,MovieVersions
  CUSTOM_MOVIE_FOLDER: /storage/symlinks/movies
  CUSTOM_SHOW_FOLDER: /storage/symlinks/series
  4K_SEPARATION: "true"
  CUSTOM_4KMOVIE_FOLDER: /storage/symlinks/movies-4k
  CUSTOM_4KSHOW_FOLDER: /storage/symlinks/series-4k
  CUSTOM_ANIME_MOVIE_FOLDER: /storage/symlinks/movies-anime
  CUSTOM_ANIME_SHOW_FOLDER: /storage/symlinks/series-anime
  CINESYNC_LAYOUT: "true"
  SLEEP_TIME: "5"
  WEBDAV_AUTH_ENABLED: "false"
  CINESYNC_WEBDAV: "true"

  # New values
  CINESYNC_AUTH_ENABLED: "false"
  MEDIAHUB_AUTO_START: "true"
  CINESYNC_API_PORT: "8082"
{{ end }}