{{ if or .Values.plex.enabled .Values.plexranger.enabled .Values.plexhobbit.enabled .Values.plexhalfling.enabled .Values.plexnazgul.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
data:
  # PLEX_PREFERENCE_1: "FriendlyName=ElfHosted | {{ .Release.Name }}"
  PLEX_PREFERENCE_2: "FSEventLibraryPartialScanEnabled=1"
  PLEX_PREFERENCE_3: "FSEventLibraryUpdatesEnabled=0"
  PLEX_PREFERENCE_4: "TranscoderPhotoFileSizeLimitMiB=10"
  # PLEX_PREFERENCE_6: "TranscodeCountLimit=3"

  # no longer enforced
  # PLEX_PREFERENCE_7: "autoEmptyTrash=0"
  PLEX_PREFERENCE_8: "BackgroundTranscodeLowPriority=1"
  PLEX_PREFERENCE_9: "LongRunningJobThreads=1"
  PLEX_PREFERENCE_11: "RelayEnabled=0"
  PLEX_PREFERENCE_12: "TranscoderTempDirectory=/transcode"
  PLEX_PREFERENCE_13: "MinutesAllowedPaused=30"
  PLEX_PREFERENCE_14: "GenerateIntroMarkerBehavior=scheduled"
  PLEX_PREFERENCE_16: "ButlerEndHour=10"
  PLEX_PREFERENCE_17: "ButlerTaskDeepMediaAnalysis=0" # this wrecks remote mounts
  PLEX_PREFERENCE_18: "ButlerTaskUpgradeMediaAnalysis=0" # suspect this does too

  PLEX_PREFERENCE_15: "ButlerStartHour=9"
  PLEX_PREFERENCE_10: "TranscoderH264BackgroundPreset=ultrafast"
  PLEX_PREFERENCE_19: "MarkerSource=cloud" # get credit markers from online DBs only
  PLEX_PREFERENCE_20: "GenerateCreditsMarkerBehavior=never" # don't scan for credits
  PLEX_PREFERENCE_21: "GenerateChapterThumbBehavior=never" # don't generate thumbnails
  PLEX_PREFERENCE_23: "GenerateIntroMarkerBehavior=never" # don't detect intros for skippage
  PLEX_PREFERENCE_24: "GenerateBIFBehavior=never" # don't generate video preview thumbnails
  PLEX_PREFERENCE_25: "GenerateAdMarkerBehavior=never" # don't detect ads for skippage
  
  PLEX_PREFERENCE_26: "LoudnessAnalysisBehavior=never"
  PLEX_PREFERENCE_27: "MusicAnalysisBehavior=never"
  PLEX_PREFERENCE_28: "GenerateVADBehavior=never"
  PLEX_PREFERENCE_29: "ScannerLowPriority=0"
  PLEX_PREFERENCE_30: "ButlerTaskRefreshLibraries=0"
  PLEX_PREFERENCE_31: "ButlerTaskRefreshLocalMedia=0"
  PLEX_PREFERENCE_32: "ButlerDatabaseBackupPath=/backup/"
  PLEX_PREFERENCE_33: "DatabaseCacheSize=1024"

  # For custom domains
  {{- if .Values.plexcustomdomain.enabled }}
  ADVERTISE_IP: "https://{{ .Values.plexcustomdomain.cname | lower }}:443"
  {{ else }}
  ADVERTISE_IP: "https://{{ .Release.Name }}-plex.{{ .Values.dns_domain }}:443"
  {{ end }}

  # to ensure VPN is up first
  WAIT_FOR_VPN: "true"

  # Use this to email transcoding-kill emails
  EMAIL_TO: {{ .Values.email }}
  SMTP_PORT: "587"
  SMTP_FROM: 'transcode-killer@elfhosted.com'

  # To check for mounts before starting
  WAIT_FOR_MOUNT_PATHS: {{ $dirs := list }}
    {{ if .Values.rclonemountrealdebridzurg.enabled }}{{ $dirs = append $dirs "/storage/realdebrid-zurg/__all__" }}{{- end }}
    {{- if .Values.rclonealldebrid.enabled }}{{ $dirs = append $dirs "/storage/alldebrid/magnets" }}{{- end }}
    {{- join "," $dirs }}

  WAIT_FOR_URLS: {{ $urls := list }}
    {{ if .Values.rclonemountrealdebridzurg.enabled }}{{ if .Values.decypharr.enabled }}{{ $urls = append $urls "http://decypharr:8282/webdav/realdebrid/version.txt" }}{{- else }}{{ $urls = append $urls "http://zurg:9999/http/version.txt" }}{{- end }}{{- end }}
    {{- if .Values.rclonealldebrid.enabled }}{{ $urls = append $urls "http://alldebrid:9999" }}{{- end }}
    {{- join "," $urls }}

{{ end }}