{{ if or .Values.emby.enabled .Values.embyranger.enabled .Values.embyhobbit.enabled .Values.embyhalfling.enabled .Values.embynazgul.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: emby-env
data:
  # To check for mounts before starting
  WAIT_FOR_MOUNT_PATHS: {{ $dirs := list }}
    {{ if .Values.rclonemountrealdebridzurg.enabled }}{{ $dirs = append $dirs "/storage/realdebrid-zurg/__all__" }}{{- end }}
    {{- if .Values.rclonealldebrid.enabled }}{{ $dirs = append $dirs "/storage/alldebrid/magnets" }}{{- end }}
    {{- join "," $dirs }}

  WAIT_FOR_URLS: {{ $urls := list }}
    {{ if .Values.rclonemountrealdebridzurg.enabled }}{{ if .Values.decypharr.enabled }}{{ $urls = append $urls "http://decypharr:8282/webdav/realdebrid/version.txt" }}{{- else }}{{ $urls = append $urls "http://zurg:9999/http/version.txt" }}{{- end }}{{- end }}
    {{- if .Values.rclonealldebrid.enabled }}{{ $urls = append $urls "http://alldebrid:9999" }}{{- end }}
    {{- join "," $urls }}
{{ end }}