{{ if .Values.elfbot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: elfbot-env
data:
  USERNAME: {{ .Release.Name }}
  DOMAIN_SUFFIX: {{ .Values.dns_domain | default "elfhosted.com" }}
{{ end }}
