{{ if .Values.nuviostreams.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuviostreams-env
data:
  DISABLE_CACHE: "false"
  DISABLE_STREAM_CACHE: "false"
  USE_REDIS_CACHE: "false"

  VIDZEE_PROXY_URL:
  HOLLYMOVIEHD_PROXY_URL: 
  XPRIME_PROXY_URL: 
  CUEVANA_PROXY_URL: http://localhost:3000/?destination=
  CUEVANA_M3U8_PROXY_URL: https://{{ .Release.Name }}-nuviostreams-proxy.{{ .Values.dns_domain }}/m3u8-proxy
  XPRIME_USE_PROXY:

  SHOWBOX_PROXY_URL_VALUE: https://illustrious-trifle-e37594.netlify.app/?destination=
  SOAPERTV_PROXY_URL: http://localhost:3000/?destination=
  VIDSRC_PROXY_URL: http://localhost:3000/?destination=
  SHOWBOX_USE_ROTATING_PROXY: "false"  

  ENABLE_TOPMOVIES_PROVIDER: "true"
  ENABLE_VIDZEE_PROVIDER: "true"
  ENABLE_HOLLYMOVIEHD_PROVIDER: "false"
  ENABLE_XPRIME_PROVIDER: "false"
  ENABLE_CUEVANA_PROVIDER: "false"
  ENABLE_MP4HYDRA_PROVIDER: "true"
  ENABLE_HIANIME_PROVIDER: "false"
  VERCEL: "true"

  USE_SCRAPER_API: "true"
  HIANIME_SERVER: http://150.230.133.192:8082/fetch-hianime

{{ end }}
