{{ if .Values.audiobookbayautomated.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiobookbay-automated-env
data:
  ABB_HOSTNAME: audiobookbay.is
  DOWNLOAD_CLIENT: qbittorrent
  DL_HOST: decypharr
  DL_PORT: "8282"
  # DL_URL: None
  # DL_USERNAME: None
  DL_SCHEME: http
  DL_CATEGORY: audiobookbay-automated
  # SAVE_PATH_BASE: None
  NAV_LINK_NAME: Open AudioBookshelf
  NAV_LINK_URL: https://{{ .Release.Name }}-audiobookshelf.{{ .Values.dns_domain }}
{{ end }}