{{ if .Values.nuviostreams.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuviostreams-env
data:
  XPRIME_PROXY_URL: http:://vpnproxy:8888
  XPRIME_USE_PROXY: "true"
  ENABLE_XPRIME_PROVIDER: "true"
  ENABLE_HOLLYMOVIEHD_PROVIDER: "true"
  ENABLE_CUEVANA_PROVIDER: "true"
{{ end }}