{{ if .Values.nuviostreams.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuviostreams-env
data:
 
DISABLE_CACHE=false
DISABLE_STREAM_CACHE=false
USE_REDIS_CACHE=false
REDIS_URL=


SHOWBOX_PROXY_URL_VALUE=https://illustrious-trifle-e37594.netlify.app/?destination=
SHOWBOX_USE_ROTATING_PROXY=false


VIDSRC_PROXY_URL= http://localhost:3000/?destination=
VIDZEE_PROXY_URL=
SOAPERTV_PROXY_URL=
HOLLYMOVIEHD_PROXY_URL=https://illustrious-trifle-e37594.netlify.app/?destination=
XPRIME_PROXY_URL=
XPRIME_USE_PROXY=false


ENABLE_VIDZEE_PROVIDER=true
ENABLE_HOLLYMOVIEHD_PROVIDER=false
ENABLE_XPRIME_PROVIDER=false
ENABLE_CUEVANA_PROVIDER=false
ENABLE_MP4HYDRA_PROVIDER=true
ENABLE_HIANIME_PROVIDER=false


TMDB_API_KEY=439c478a771f35c05022f9feabcca01c
USE_SCRAPER_API=false
HIANIME_SERVER=
GEMINI_API_KEY=AIzaSyCHi5Gc4BDYGVxYqrLYXfNmz3oKyhPIkuA

{{ end }}
