{{ if .Values.listsync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: listsync-env
data:
  {{ if .Values.jellyseerr.enabled }}
  OVERSEERR_URL: {{ .Release.Name }}-jellyseerr.{{ .Values.dns_domain }}
  {{ else }}
  OVERSEERR_URL: {{ .Release.Name }}-overseerr.{{ .Values.dns_domain }}
  {{ end }}
  AUTOMATED_MODE: "true"
  OVERSEERR_USER_ID: "1"
  NEXT_PUBLIC_API_URL: https://{{ .Release.Name }}-listsync-backend.{{ .Values.dns_domain }}/api
{{ end }}