{{ if .Values.rclonemountdebridav.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-debridav
  namespace: csi-rclone
type: Opaque
stringData:
  remote: debridav-{{ .Release.Name }}
  remotePath: # intentionally left blank, webdav doesn't need it
  allow-non-empty: "true"
  allow-other: "true"
  uid: "568"
  gid: "568" 
  vfs-cache-mode: full
  vfs-cache-max-size: 20G
  vfs-read-chunk-size: 8M
  vfs-read-chunk-size-limit: 128M
  dir-cache-time: 60s 

  # Try to handle failures better
  low-level-retries: "2"
  retries: "2"
  retries-sleep: "5s" 
  timeout: 15s
  contimeout: "5s"
    
  # still testing these
  # retries: "1"
  # low-level-retries: "1"
  # attr-timeout: 1s
  # timeout: 10s
  # contimeout: 5s
  # vfs-read-ahead: 32M
  # tpslimit: "3" # only 3 transactions per second, is that enough?
  # end testing section
  configData: |
    [debridav-{{ .Release.Name }}]
    type = webdav
    url: http://debridav.{{ .Release.Namespace }}.svc.cluster.local:8080
    vendor = other
    pacer_min_sleep = 0
{{ end }}