{{ if .Values.rclonemountpremiumize.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-premiumize
  namespace: csi-rclone
type: Opaque
stringData:
  remote: premiumize-{{ .Release.Name }}
  remotePath: # intentionally left blank, webdav doesn't need it
  allow-non-empty: "true"
  allow-other: "true"
  attr-timeout: 1s
  uid: "568"
  gid: "568" 
  vfs-cache-mode: full
  vfs-cache-max-age: 720h
  vfs-cache-max-size: 20G
  vfs-cache-poll-interval: 30s
  async-read: "true"
  vfs-read-ahead: 64M
  vfs-read-chunk-size: 1M
  vfs-read-chunk-size-limit: 32M
  vfs-fast-fingerprint: "true"
  vfs-read-wait: 40ms
  no-modtime: "true"
  no-checksum: "true"
  poll-interval: 60s
  transfers: "40"
  checkers: "40"
  multi-thread-streams: "0"
  use-mmap: "true"
  buffer-size: 64M
  dir-cache-time: 120s
  contimeout: 10s
  timeout: 10s
  configData: |
    [premiumize-{{ .Release.Name }}]
    type = webdav
    url: http://premiumize.{{ .Release.Namespace }}.svc.cluster.local:9999
    vendor = other
    pacer_min_sleep = 0
{{ end }}