{{ if .Values.rcloneui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rclone
  namespace: csi-rclone
type: Opaque
stringData:
  remote: rclone-{{ .Release.Name }}
  remotePath: # intentionally left blank, webdav doesn't need it
  allow-non-empty: "true"
  allow-other: "true"
  attr-timeout: 1s
  uid: "568"
  gid: "568" 
  # debugging RD issues
  vfs-cache-mode: full
  vfs-cache-max-age: 1h
  vfs-cache-max-size: 20G
  async-read: "true"
  vfs-read-ahead: 128M
  vfs-read-chunk-size: 8M
  vfs-read-chunk-size-limit: 2G
  vfs-fast-fingerprint: "true"
  no-modtime: "true"
  no-checksum: "true"
  use-mmap: "true"
  buffer-size: 16M
  dir-cache-time: 10s
  contimeout: 10s
  timeout: 10s
  configData: |
    [rclone-{{ .Release.Name }}]
    type = webdav
    url: http://rcloneui.{{ .Release.Namespace }}.svc.cluster.local:5575/
    vendor = other
    pacer_min_sleep = 0    
{{ end }}