{{ if .Values.rclonemounttorbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-torbox
  namespace: csi-rclone
type: Opaque
stringData:
  remote: torbox-{{ .Release.Name }}
  remotePath: # intentionally left blank, webdav doesn't need it
  allow-non-empty: "true"
  allow-other: "true"
  uid: "568"
  gid: "568" 
  vfs-cache-mode: full
  vfs-cache-max-age: 24h
  vfs-cache-max-size: 10G
  async-read: "true"
  vfs-read-ahead: 128M
  vfs-read-chunk-size: 64M
  vfs-read-chunk-size-limit: 2G
  use-mmap: "true"
  buffer-size: 64M
  dir-cache-time: 10s
  bwlimit: 20M
  configData: |
    [torbox-{{ .Release.Name }}]
    type = ftp
    user: {{ .Values.rclonemounttorbox.username }}
    pass: {{ .Values.rclonemounttorbox.password }} 
    host = ftp.torbox.app
    tls = false
    explicit_tls = true
{{ end }}