{{ if .Values.rcloneui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rclone
  namespace: csi-rclone
type: Opaque
stringData:
  remote: rclone-{{ .Release.Name }}
  remotePath: # intentionally left blank, webdav doesn't need it
  allow-non-empty: "true"
  allow-other: "true"
  attr-timeout: 7d
  uid: "568"
  gid: "568" 
  # debugging RD issues
  vfs-cache-mode: full
  vfs-cache-max-age: 72h
  vfs-cache-max-size: 50G
  async-read: "true"
  max-read-ahead: 200M
  vfs-read-ahead: 2M
  vfs-read-chunk-size: 2M
  vfs-read-chunk-size-limit: 32M
  vfs-fast-fingerprint: "true"
  vfs-cache-poll-interval: 30s
  vfs-read-wait: 100ms
  no-modtime: "false"
  no-checksum: "true"
  use-mmap: "true"
  buffer-size: "0"
  dir-cache-time: 10s # we are only querying decypharr/zurg, not rd, so I don't think this low rate is a problem
  contimeout: 10s
  timeout: 10s
  configData: |
    [rclone-{{ .Release.Name }}]
    type = webdav
    url: http://rcloneui.{{ .Release.Namespace }}.svc.cluster.local:5575/
    vendor = other
    pacer_min_sleep = 0    
{{ end }}