{{ if .Values.nuviostreams.enabled }}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "nuviostreams-env",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "nuviostreams-env",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "TMDB_API_KEY": "AgCpDl/9XLE5VyTVsb5hXpP7p6PWgxJym4wUIF7JQrkZvq6HAyprEALzUGBmP3ZEoQP0ebjMCsqx1fV10yCuvNNfcSWTqBPsyK+Hp7wN90ULEjJ3lr7U8WGWouDO3NBGGffjoh9cH6e9eyFGFzJIM5TgtJFcpuJbmbUe/FhLAfZMJAxjGTOqW+UB+Tj40GO7d9PKWzhUPKBfISt52KuoiH/X4b+lJRxjZRr0RKk2vUOwSlXFKlLX4IAdZpDyGaEzytnb2MnpuKLk8fBEulOYeJ6vNTjN5tMX+vU5nG2IEKAnk3NlQXzrhUwH9VUBD/cHUjs+ISSdQM6DceJANC1zjvNf0hVrRh02iIUnNBmA+RUZyzn+HEjUAWJ/LFrjLK2906xxxFbuQE8oZ4hhFGNMJ0xc5Fk471H3dSjhiVOZs25Nh+8Fdzqqsjz4de4KK9j4rdfqP4ieDXChPYZE3arEByeGuvIuiGsM2GyaVIVkIcVjcValc4nbDfqVGa2+ElCBINFCgWHsfJF0Ioud+Jc2Lf1c5uHVHx0TMVbjXn4gjRRhXoG9jhOEl1G6pOBxC8mhudNUHE8K7JKkA0ViKD1KqMWklktSxo1vxcRGeDnOxHrDW0xw94RhRxipkTlLjmUW5wgACHGHnaNEHmuZVE9b6p4zIlMu4DhjCphO4LBIFQe+2YyDTm4V/vmXVcQ6QSzwYzp4Ddz8eZ2hup+CCbohpM7yE4Bs/Sc7DCLfviBSl5d2Zw=="
    }
  }
}
{{ end }}
