{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "aiostreams-env",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "aiostreams-env",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "SECRET_KEY": "AgAKTQQ8Ih5RF5X1MNKVb1ApJvFnSVPYE+w9E2NgArrYt/dq+o2OryxJiGzDuOrLmPp4ZH2RsrhX1VnQrRABgOyveUSi2LDHTwDYB6Z3bTBalgiSP54WEWJYEt8jQSTFiKmED2FDuZLJkH6lA0PZZFxGrCLCWQFK2/dS/+OAY7kiYPBXWUpr90auDv+PWUCFRcXv6sul+ghn8KEcGpRDzGBNnRJfxvq9xOBDXkKrkpMcUMC9F98gUXK7YOKn/7Pu0qRcrsba+6gC0iS+3OQdoZOstIkvmf08exhDbqUA43tk/PZtJYIcoCAT10lFzUKxk/AUMlzzfllbs0syeMBFMGOJyLKp3Ediw4ZNwDGNqB/O9mmgAXjTKk3E5PPIy8esqbvgmO1PX3jY/j3NPO1faemOI9PzBN1LRpmFfYyGI25jUUGz42YGMK65aGf0NJSdFyN5uAzgxYk7TGCA4rV3tPG0ZLPcfjX+gGFUcTK6YMVhcfJsc5hleIhbrkIpGBXwFogJb2XWLeIFaIhLUMu4eQ+VkUApRlJXG6VhbM2cNvpr6+D90qLRiHgAEBeY8mDlMsL6hcn+zLglN6PmdOuZ50vAOf1ZiUscwThMziM851wg0iAhm/RU1KmTRXSEu9URgnVeEKJXS1xiVulTBcTukKRfvlaZGeblhMXvqL5W4dQgFpd9mOZci0kPaflBQmnLm110FX+/8h552Vj6C0OEEWO2pJhPRakv8SMIbRbj2TZlFuKfT2+AqAXzUB5RuV0K6sT7D+JQn5gylO52H3+IVUGywm1p8AECKTp8GyqbCv02tXzc0sa+9cjkpeYOeWYT3/k6+Dyn/7eaXw+pPI2zH2MmT3CvZxioPctgrvNgL8rnsQ==",
      "TMDB_ACCESS_TOKEN": "AgAy4hxII7vj2EnCf6bnoKo2i8wj9QC9/DxUlQk+BEh/eqxJwBHWnKf7DffafIAhKNHM79L1a4Z86x19kE8yzCLIwFyCUiKt15cFRcXdgDrEDdhyHLWReJxZXT7zz8RXm8UDGCgxgVZYimSTnfL6EYMaNf3kSZGVQLgE19xUOtgWjT74R4M0iYzP5MY8M00FFbCjThu2+HoY2ehvgkxpSDdcNBFgVdNG/g9zqrcGvs8Sw/MtPaW6v95uxD1grH6E5kcWLmgNR22T7Jq6Ho+T/dAbqQz0uckoamjR3lEj74Z+NH2mbG++rN8yg36fmHWWnjRsLW2BdDRzGR6qzmwdLbEPT7j1B9/0Bisva7P0PSbTCO7YuQswcNQyO2uJ8XQoHOqpDjhZTreHJLx235BVQ2GsCegl7svT0hh5UynDbCRN80TB/PPSL8PpkQX2z0HKWmpwTDKxMfeAZY0B4uEUgswEiksn12KqLofkJlXN9a8pFp+0KVs2M/Lf4jr9l+3xXjv95Griypy3qo5vJ6aCoqKDEW3Zsvn1C6AQXM1Ll5PJNhsE5ep1dAOV3Zgcn25hIIILBXra53kJR58eHOogz4JDKg8HKn75qPHUykQzHymncmBAisPM2Y62LVApPGQZGoo6v/pV8l7gqMk1YPZ18WbXm38uS1kc64Wex/ffGzJVAFjxDKlfc6Brq2WUd/tfvI1uIbag+KLvNWI+RCiuPUnnq3dqWEiU9ZSZJw5MzV/g+VT0I1o/iK1rc5/LoUzvloaFxZ6mzJbZ2ruQfPa2kg88QD0C9w0EOzqTV/GiMf5WukvEHmcmhWN8omfaXaEyM+YYbgKklpmTQSHU3CStLisfE8MzvnYpaQfTJwTsQrRriO0wT0nOr/Vqf63llatsqWIEpD2IaS3I298DbcSpDPB0dL9oXiaxR47PcsvFSKgaTLPYSAuhVeo06E3VZ0HQQtXcSuCcZxN1YcLXQlrmaAx5kHbz"
    }
  }
}
