{{ if .Values.nuviostreams.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "permit-nuviostreams-egress-nuviostreams-redis"
spec:
  endpointSelector:
    matchLabels:
      app.elfhosted.com/name: nuviostreams
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: nuviostreams
        app.kubernetes.io/name: redis
    toPorts:
      - ports:
        - port: '6379'
          protocol: TCP
{{ end }}