{{ if .Values.elfbot.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "permit-elfbot-egress-kube-apiserver"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: elfbot
  egress:
    - toEntities:
        - kube-apiserver
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "6443"
{{ end }}