apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-add-cors-for-homer
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "https://{{ .Release.Name }}.elfhosted.com"
      - "https://{{ .Release.Name }}.elfhosted.cc"  
      - "https://{{ .Release.Name }}.elfhosted.party"    
      - "https://{{ .Release.Name }}.ci-elfhosted.com"
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
    accessControlAllowHeaders:
    - "*"