name: notify discord

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:

    - name: Github Releases To Discord
      uses: SethCohen/github-releases-to-discord@v1.13.1
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        color: "5273134"
        username: "Spanky the ElfBot"
        avatar_url: "https://github.com/spanky-the-elfbot.png"
        content: <@&1391914584440311840>, it's rollout time! Here's what's new...
        footer_title: "If your particular apps are affected, you can expect them to restart briefly within the next hour"
        footer_icon_url: "https://github.com/elfhosted.png"
        footer_timestamp: true                        