kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elfbot
subjects:
- kind: ServiceAccount
  name: filebrowser
- kind: ServiceAccount
  name: elfbot  
roleRef:
  kind: Role
  name: elfbot
  apiGroup: rbac.authorization.k8s.io