kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elfbot
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
# Used for force-deletion
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["delete","list","get","watch"]
# Used to trigger backups
- apiGroups: ["volsync.backube"]
  resources: ["replicationsources"]
  verbs: ["list","get","update","patch"]